#!/usr/bin/env python3
"""
Generate a header with two version strings for the binary-signature
.mcu_info block:

  TLK_SDK_GIT_VERSION - the *original* Telink UniSDK version. Prefers a
      frozen VERSION file at the SDK root (written once by release/export
      tooling), so it keeps identifying the SDK release even after the SDK
      is exported and/or vendored inside a customer's own git repository -
      where `git describe` on the SDK directory would otherwise silently
      report the customer's tags/commits instead of the SDK's own. Falls
      back to `git describe` in the SDK repo when no VERSION file exists
      (this is the case in an SDK developer checkout, like this one).

  TLK_APP_GIT_VERSION - the user application's own version: always
      `git describe` in the application's source directory, which is
      expected to be a separate, live git repository.

Re-run on every build (see cmake/modules/version.cmake) so both versions
always reflect the current source trees, including a "-dirty" suffix for
uncommitted changes. The output file is only rewritten when its content
actually changes, so an unchanged version does not force a rebuild.

Author: Telink Semiconductor
License: Apache-2.0
"""

import argparse
import subprocess
import sys
from pathlib import Path


def git_describe(repo_dir):
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_dir), "describe", "--tags", "--always", "--dirty"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=True,
        )
        return out.stdout.decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return "unknown"


def get_sdk_version(repo_dir, version_file):
    if version_file and version_file.is_file():
        text = version_file.read_text().strip()
        if text:
            return text
    return git_describe(repo_dir)


def get_app_version(repo_dir):
    return git_describe(repo_dir)


def render_define(name, value, max_len):
    # Reserve one byte for the NUL terminator, since this is placed in a
    # fixed-size flash field (see tlk_mcu_info.c) that must never overflow.
    value = value[: max(max_len - 1, 0)]
    return f'#define {name} "{value}"\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, help="Path of the header file to generate")
    parser.add_argument("--sdk-repo", required=True, help="Path to the SDK git repository (TELINK_BASE)")
    parser.add_argument(
        "--sdk-version-file",
        required=True,
        help="Frozen SDK VERSION file, checked before falling back to git describe",
    )
    parser.add_argument("--sdk-max-len", type=int, required=True)
    parser.add_argument("--app-repo", required=True, help="Path to the application's git repository")
    parser.add_argument("--app-max-len", type=int, required=True)
    args = parser.parse_args()

    sdk_version = get_sdk_version(Path(args.sdk_repo), Path(args.sdk_version_file))
    app_version = get_app_version(Path(args.app_repo))

    content = (
        "/* Auto-generated by git_version_gen.py - do not edit by hand. */\n"
        "#pragma once\n"
        + render_define("TLK_SDK_GIT_VERSION", sdk_version, args.sdk_max_len)
        + render_define("TLK_APP_GIT_VERSION", app_version, args.app_max_len)
    )

    output_path = Path(args.output)
    if output_path.exists() and output_path.read_text() == content:
        return 0

    output_path.write_text(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
