stages:
  - build

run_builds:
  stage: build
  tags:
    - LINUX
  before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip3 install west
  - rm -rf ../.west
  - west init -l .
  - URL=$(west list tinyusb -f "{url}")
  - REV=$(west list tinyusb -f "{revision}")
  - MOD_PATH=$(west list tinyusb -f "{path}")
  - mkdir -p ../$MOD_PATH && cd ../$MOD_PATH
  - git init
  - git remote add origin $URL
  - git fetch --depth 1 origin $REV
  - git checkout FETCH_HEAD
  - cd -
  script:
    - export TELINK_TOOLCHAIN_PATH='/opt/TelinkIDE/RDS/V5.3.x/toolchains/nds32le-elf-mculib-v5f'
    - export COMPILER_BIN="${TELINK_TOOLCHAIN_PATH}/bin"
    - export PATH="$PATH:$COMPILER_BIN"
    - riscv32-elf-gcc --version
    - pip3 install --timeout 100 --retries 10 --progress-bar off -r ./ci_configs/requirements.txt
    - chmod +x ./scripts/ci/ci_prepare.sh ./scripts/ci/ci_build.sh ./scripts/ci/ci_build_all.sh
    - ./scripts/ci/ci_build_all.sh
  artifacts:
    when: always
    paths:
      - ci_logs/