# The west manifest file for Telink.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want.
#
# See the west documentation for more information.

manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: tinyusb
      url: https://github.com/hathach/tinyusb.git
      revision: 3af1bec1a9161ee8dec29487831f7ac7ade9e189
      path: unisdk/modules/tinyUSB/repo

    - name: mbedtls
      url: https://github.com/Mbed-TLS/mbedtls.git
      revision: ece41aa84d7879d7e55c59e955a5884b541f7f3b
      submodules: true
      path: unisdk/modules/mbedtls/repo

    - name: ble_controller
      url: http://192.168.48.36/sdk_app/unisdk/unisdk_component/subsystem/ble_controller
      revision: 36a4f99c1a85d6fb5b416429aeab854d3a058915
      path: unisdk/subsystem/ble/controller
  self:
    path: unisdk
    west-commands: scripts/west-commands.yml
