/********************************************************************************************************
 * @file    tlk_mcu_info.c
 *
 * @brief   MCU-info block placed at a fixed flash address
 *
 * @author  Telink UTC
 * @date    2026
 *
 * @par     Copyright (c) 2025, Telink Semiconductor (Shanghai) Co., Ltd. ("TELINK")
 *          All rights reserved.
 *
 *          Redistribution and use in source and binary forms, with or without
 *          modification, are permitted provided that the following conditions are met:
 *
 *              1. Redistributions of source code must retain the above copyright
 *              notice, this list of conditions and the following disclaimer.
 *
 *              2. Unless for usage inside a TELINK integrated circuit, redistributions
 *              in binary form must reproduce the above copyright notice, this list of
 *              conditions and the following disclaimer in the documentation and/or other
 *              materials provided with the distribution.
 *
 *              3. Neither the name of TELINK, nor the names of its contributors may be
 *              used to endorse or promote products derived from this software without
 *              specific prior written permission.
 *
 *              4. This software, with or without modification, must only be used with a
 *              TELINK integrated circuit. All other usages are subject to written permission
 *              from TELINK and different commercial license may apply.
 *
 *              5. Licensee shall be solely responsible for any claim to the extent arising out of
 * or relating to such deletion(s), modification(s) or alteration(s).
 *
 *          THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *          ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *          WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *          DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY
 *          DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *          (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *          LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *          ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *          (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *          SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *******************************************************************************************************/
/*
 * CONFIG_TLK_CORE is generated by Kconfig (see core/Kconfig) and expands to a bare
 * token such as TL721X - stringify it the same way tlk_sdk_version.h stringifies
 * the SDK version macro.
 */
#define UNISDK_MCU_NAME_STR1(x) #x
#define UNISDK_MCU_NAME_STR(x)  UNISDK_MCU_NAME_STR1(x)

/*
 * Field widths come from Kconfig (core/configs/Kconfig.common) so the struct
 * layout can never drift from the space flash_boot.link reserves for
 * .mcu_info. Each field is zero-padded to its configured width, so the
 * section always occupies exactly the reserved size regardless of name length.
 */
typedef struct
{
    char tlk_mcu_core[CONFIG_TLK_BINARY_SIGNATURE_CORE_NAME_SIZE];
    char tlk_mcu_soc[CONFIG_TLK_BINARY_SIGNATURE_SOC_NAME_SIZE];
    char tlk_mcu_case[CONFIG_TLK_BINARY_SIGNATURE_SOC_CASE_NAME_SIZE];
    char tlk_sdk_version[CONFIG_TLK_BINARY_SIGNATURE_SDK_VERSION_SIZE];
    char tlk_app_version[CONFIG_TLK_BINARY_SIGNATURE_APP_VERSION_SIZE];
} tlk_mcu_info;

/*
 * TLK_SDK_GIT_VERSION and TLK_APP_GIT_VERSION are generated by
 * scripts/generators/git_version_gen.py (see cmake/modules/version.cmake) on
 * every build, already truncated to fit their reserved Kconfig sizes:
 *  - TLK_SDK_GIT_VERSION identifies the original UniSDK sources: a frozen
 *    VERSION file at the SDK root if the release/export tooling dropped one,
 *    otherwise git describe (tag, or short commit hash, "-dirty" suffixed)
 *    of TELINK_BASE. The frozen file keeps this correct even if the SDK is
 *    vendored inside the application's own git repo.
 *  - TLK_APP_GIT_VERSION identifies the user application: always git
 *    describe of APPLICATION_SOURCE_DIR, the application's own repo.
 */
__attribute__((section(".mcu_info"), used)) const tlk_mcu_info g_tlk_mcu_name = {
    .tlk_mcu_core    = UNISDK_MCU_NAME_STR(CONFIG_TLK_CORE),
    .tlk_mcu_soc     = UNISDK_MCU_NAME_STR(CONFIG_TLK_SOC),
    .tlk_mcu_case    = UNISDK_MCU_NAME_STR(CONFIG_TLK_CASE),
    .tlk_sdk_version = TLK_SDK_GIT_VERSION,
    .tlk_app_version = TLK_APP_GIT_VERSION,
};
