// Auto-generated from YAML

#define UNISDK_I2C_COUNT 2
#define UNISDK_I2C_0_SUPPORTS_MASTER_MODE true
#define UNISDK_I2C_0_SUPPORTS_MASTER_DMA true
#define UNISDK_I2C_0_SUPPORTS_SLAVE_MODE true
#define UNISDK_I2C_0_SUPPORTS_SLAVE_DMA false
#define UNISDK_I2C_1_SUPPORTS_MASTER_MODE true
#define UNISDK_I2C_1_SUPPORTS_MASTER_DMA false
#define UNISDK_I2C_1_SUPPORTS_SLAVE_MODE false
#define UNISDK_I2C_1_SUPPORTS_SLAVE_DMA false
