// Auto-generated from YAML

#define UNISDK_SPI_COUNT 2
#define UNISDK_SPI_0_SUPPORTS_MASTER_ROLE true
#define UNISDK_SPI_0_SUPPORTS_SLAVE_ROLE true
#define UNISDK_SPI_1_SUPPORTS_MASTER_ROLE true
#define UNISDK_SPI_1_SUPPORTS_SLAVE_ROLE true
