#!/bin/bash

# SDK Exporter Script
# Exports the SDK with prebuilt static libraries (sources are hidden for closed-source distribution)
#
# Usage:
#   Linux / macOS:        bash scripts/sdk_exporter.sh /path/to/export
#   Windows (Git Bash):   bash scripts/sdk_exporter.sh /d/path/to/export
#   Windows (WSL):        bash scripts/sdk_exporter.sh /mnt/d/path/to/export

set -e

sdk_dir="unisdk"
library_builder="./scripts/lib_builder/lib_builder.sh"
supported_soc_series=("TL321X" "TL721X" "TLSR952X")


# --- Argument validation ---

if [ "$#" -ne 1 ]; then
  echo "[sdk_exporter.sh] Use: $0 <export_sdk_path>"
  exit 1
fi

# Resolve to absolute Unix-style path (works with relative and absolute paths on all platforms)
sdk_export_path=$(cd "$1" && pwd)

if [ ! -d "scripts" ]; then
    echo "[sdk_exporter.sh] Run script from SDK root"
    exit 1
fi

if [ ! -d "$sdk_export_path" ]; then
    echo "[sdk_exporter.sh] Invalid SDK export path"
    exit 1
fi

if [ ! -w "$sdk_export_path" ]; then
    echo "[sdk_exporter.sh] Not writable SDK export path"
    exit 1
fi


# --- Prepare export directory ---

sdk_export_dir="$sdk_export_path/$sdk_dir"

rm -rf "$sdk_export_dir"
mkdir -p "$sdk_export_dir"

echo "[sdk_exporter.sh] Exporting to $sdk_export_dir"

# Export all tracked sources via git archive (avoids copying untracked/ignored files)
git archive --format=tar --output="$sdk_export_dir/tmp.tar" HEAD
tar -xf "$sdk_export_dir/tmp.tar" -C "$sdk_export_dir"
rm -f "$sdk_export_dir/tmp.tar"

mkdir -p "$sdk_export_dir/libraries"


# --- Precompute Windows-style PWD once (used for path normalization on Windows/Git Bash) ---
# CMake on Windows outputs paths like D:/.../..., while bash PWD is /d/.../...
# We convert PWD to Windows format so we can strip it from CMake-generated paths

drive=$(echo "$PWD" | sed 's|^/\([a-zA-Z]\)/.*|\1|' | tr '[:lower:]' '[:upper:]') # extract drive letter and uppercase it
rest=$(echo "$PWD" | sed 's|^/[a-zA-Z]/||')                                       # strip the leading /d/ part
win_pwd="${drive}:/${rest}"                                                       # assemble D:/.../...


# --- Build libraries and remove closed sources ---

for soc_series in "${supported_soc_series[@]}"; do
    echo "[sdk_exporter.sh] Building library for $soc_series (Andes)"

    # 1a. Build the Andes variant
    $library_builder $soc_series

    # Read hardware identifiers from chip.config generated by lib_builder
    core=$(grep 'CONFIG_TLK_CORE=' build/chip.config | sed 's/CONFIG_TLK_CORE="\?\([^"]*\)"\?/\1/' | tr -d '\r')
    board=$(grep 'CONFIG_TLK_BOARD=' build/chip.config | sed 's/CONFIG_TLK_BOARD="\?\([^"]*\)"\?/\1/' | tr -d '\r')

    # 2. Copy all built static libraries for this SOC into the export
    cp build/libraries/libtelink-unisdk-${soc_series}*.a "$sdk_export_dir/libraries/"

    # 1b. Build the Zephyr variant
    echo "[sdk_exporter.sh] Building library for $soc_series (Zephyr)"
    $library_builder -t zephyr $soc_series
    cp build/libraries/libtelink-unisdk-${soc_series}*.a "$sdk_export_dir/libraries/"

    # 3. Copy preprocessed Kconfig files for this SOC into export
    mkdir -p "$sdk_export_dir/kconfig/$soc_series"
    cp -r "build/Kconfig/." "$sdk_export_dir/kconfig/$soc_series/"

    # 4. Copy generated headers into export dir
    cp -r "build/generated/core/$core/."      "$sdk_export_dir/core/$core/"
    cp -r "build/generated/soc/$soc_series/." "$sdk_export_dir/soc/$soc_series/"

    if [ -n "$board" ]; then
        cp -r "build/generated/boards/$board/." "$sdk_export_dir/boards/$board/"
    fi

    # 4. Removing the source files
    used_sources_file="build/libraries/telink-unisdk-${soc_series}_sources.txt"

    if [ -f "$used_sources_file" ]; then
        echo "[sdk_exporter.sh] Removing source files for $soc_series from export directory"

        while IFS= read -r src_file_abs; do
            # Step 1: normalize the path from CMake:
            #   - remove Windows CR (\r) from CRLF line endings
            #   - convert backslashes to forward slashes (Windows CMake uses both)
            #   - collapse redundant /./  segments (e.g. soc/TL321X/./drivers -> soc/TL321X/drivers)
            src_norm=$(echo "$src_file_abs" | tr -d '\r' | tr '\\' '/' | sed 's|/\./|/|g')

            # Step 2: strip the project root prefix to get a relative path
            # Try Unix-style PWD first (Linux / macOS / WSL)
            rel_src="${src_norm#${PWD}/}"

            # If nothing was stripped — CMake gave a Windows-style path (D:/...)
            # Try again using the Windows-style PWD we computed above
            if [ "$rel_src" = "$src_norm" ]; then
                rel_src="${src_norm#${win_pwd}/}"
            fi

            rm -f "$sdk_export_dir/$rel_src"
        done < "$used_sources_file"
    else
        echo "[sdk_exporter.sh] Warning: $used_sources_file not found. Sources won't be hidden."
    fi

    echo ""
done


# --- Remove YAML files — replaced by generated headers in the exported SDK ---
echo "[sdk_exporter.sh] Removing YAML files"

find "$sdk_export_dir/core"   -path "*/properties/*.yaml" -delete
find "$sdk_export_dir/core"   -path "*/registers/*.yaml"  -delete
find "$sdk_export_dir/soc"    -path "*/properties/*.yaml" -delete
find "$sdk_export_dir/soc"    -path "*/registers/*.yaml"  -delete
find "$sdk_export_dir/boards" -name "*.yaml" -delete


# --- Remove internal scripts from export (not intended for SDK users) ---
echo "[sdk_exporter.sh] Removing scripts"

rm -rf "$sdk_export_dir/scripts/lib_builder"
rm -f  "$sdk_export_dir/scripts/sdk_exporter.sh"
