// Auto-generated from YAML

#define UNISDK_PM_RETENTION_SIZES_COUNT 3
#define UNISDK_PM_RETENTION_SIZES_0 32
#define UNISDK_PM_RETENTION_SIZES_1 64
#define UNISDK_PM_RETENTION_SIZES_2 96
#define UNISDK_PM_SUSPEND_O2_CODE_US 498
#define UNISDK_PM_SUSPEND_OS_CODE_US 632
#define UNISDK_PM_SUSPEND_POWER_GATE_MASK 0x87
#define UNISDK_PM_SLEEP_DEEP_SLEEP_RC_DELAY_US 688
#define UNISDK_PM_SLEEP_DEEP_SLEEP_XTAL_DELAY_US 688
#define UNISDK_PM_SLEEP_DEEP_RETENTION_SUSPEND_RC_DELAY_US 188
#define UNISDK_PM_SLEEP_DEEP_RETENTION_SUSPEND_XTAL_DELAY_US 200
#define UNISDK_PM_WAKEUP_STATUS_MAX_CLR_TIMES 3
#define UNISDK_PM_BOOT_ROM_US 380
#define UNISDK_PM_HARDWARE_DELAY_US 109
#define UNISDK_PM_MAX_SLEEP_DURATION_TIMER_TICKS 0xE0000000
#define UNISDK_PM_32K_RC_START_LONG_SLEEP_TICKS 0x0fff0000
#define UNISDK_PM_32K_XTAL_START_LONG_SLEEP_TICKS 0x03ff0000
#define UNISDK_PM_REG_WAKEUP_POLARITY 0x3f
#define UNISDK_PM_REG_WAKEUP_ENABLE 0x45
#define UNISDK_PM_REG_AON_WAKEUP_ENABLE 0x4b
#define UNISDK_PM_REG_POWERON_BUFFER_CLEAR 0x3a
#define UNISDK_PM_REG_WAKEUP_STATUS 0x64
#define UNISDK_PM_REG_XO_CLOCK_CONFIG 0x4e
#define UNISDK_PM_REG_POWERDOWN_CTRL 0x05
#define UNISDK_PM_REG_POWERDOWN_AUTO_CTRL 0x4c
#define UNISDK_PM_REG_POWERGATE_CTRL 0x7d
#define UNISDK_PM_REG_ANALOG_MISC_CTRL 0x0b
#define UNISDK_PM_REG_LDO_TRIM_CTRL 0x02
#define UNISDK_PM_REG_POWERDOWN_LDO_CTRL 0x06
#define UNISDK_PM_REG_SRAM_POWER_CTRL 0x7e
#define UNISDK_PM_REG_POWERDOWN_AUTO_SEQ 0x4d
#define UNISDK_PM_REG_LDO_CLK_TRIM_CTRL 0x09
#define UNISDK_PM_REG_BG_LDO_TRIM_CTRL 0x00
#define UNISDK_PM_REG_XTAL_DELAY_CTRL 0x3d
#define UNISDK_PM_REG_DELAY_COUNTER 0x3e
#define UNISDK_PM_REG_SYSTEM_BOOT_CTRL 0x7f
#define UNISDK_PM_REG_BUSCLK_RATIO 0x1401d8
#define UNISDK_PM_REG_MSPI_MODE_CTRL 0x1401c0
#define UNISDK_PM_REG_MSPI_CFG 0x23FFFF20
#define UNISDK_PM_BFLD_XO_QUICK_SETTING TLK_BIT_RNG(0, 1)
#define UNISDK_PM_BFLD_XO_ISEL_PMU TLK_BIT_RNG(2, 5)
#define UNISDK_PM_BFLD_XO_EN_48M_PMU TLK_BIT(6)
#define UNISDK_PM_BFLD_CLK32K_SEL TLK_BIT(7)
#define UNISDK_PM_BFLD_PD_NVT_1P2 TLK_BIT(0)
#define UNISDK_PM_BFLD_PD_NVT_2P0 TLK_BIT(1)
#define UNISDK_PM_BFLD_PM_PD_VOICE_DET_1P0V TLK_BIT(2)
#define UNISDK_PM_BFLD_COMP_REF_MOD_SEL TLK_BIT(3)
#define UNISDK_PM_BFLD_COMP_REFSCALE TLK_BIT_RNG(4, 5)
#define UNISDK_PM_BFLD_MSCN_PULLUP_RES_ENB TLK_BIT(6)
#define UNISDK_PM_BFLD_DP_PULLUP_RES_3V TLK_BIT(7)
#define UNISDK_PM_BFLD_LDO_RET_TRIM TLK_BIT_RNG(0, 2)
#define UNISDK_PM_BFLD_LDO_FLASH_EN_BYPASS TLK_BIT(3)
#define UNISDK_PM_BFLD_LDO_SPD_TRIM TLK_BIT_RNG(4, 6)
#define UNISDK_PM_BFLD_EN_VO_2P2 TLK_BIT(7)
#define UNISDK_PM_BFLD_SUSPEND_MODE 0x00
#define UNISDK_PM_BFLD_DEEP_SLEEP_MODE 0x70
#define UNISDK_PM_BFLD_RETENTION_MODE_SIZE_32K 0x61
#define UNISDK_PM_BFLD_RETENTION_MODE_SIZE_64K 0x43
#define UNISDK_PM_BFLD_RETENTION_MODE_SIZE_96K 0x07
